# Generated by Django 3.1.4 on 2020-12-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person_name', models.CharField(max_length=64)),
                ('delivery_person_phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Person',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Food Category',
            },
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='appadmin.foodcategory')),
            ],
            options={
                'verbose_name_plural': 'Food Details',
            },
        ),
        migrations.CreateModel(
            name='CustOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('estimated_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_status', models.CharField(blank=True, max_length=64, null=True)),
                ('order_address', models.CharField(blank=True, max_length=64, null=True)),
                ('bill_amount', models.IntegerField(blank=True, null=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_id', to=settings.AUTH_USER_MODEL)),
                ('delivery_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_id', to='appadmin.deliveryperson')),
            ],
            options={
                'verbose_name_plural': 'Customer Order Status',
            },
        ),
        migrations.CreateModel(
            name='CustOrderSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to='appadmin.fooddetails')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='appadmin.custorderstatus')),
            ],
            options={
                'verbose_name_plural': 'Customer Order Selection',
            },
        ),
    ]
