# Generated by Django 3.1.4 on 2020-12-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0002_fooddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person_name', models.CharField(max_length=64)),
                ('delivery_person_phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Person',
            },
        ),
    ]
