# Generated by Django 3.1.4 on 2020-12-19 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appadmin', '0003_deliveryperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('estimated_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_status', models.CharField(blank=True, max_length=64, null=True)),
                ('order_address', models.CharField(blank=True, max_length=64, null=True)),
                ('bill_amount', models.IntegerField(blank=True, null=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_id', to=settings.AUTH_USER_MODEL)),
                ('delivery_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_id', to='appadmin.deliveryperson')),
            ],
            options={
                'verbose_name_plural': 'Customer Order Status',
            },
        ),
    ]
